### ISSUE TITLE
NDI Windows Installer - download server for NDI runtime is unavailable

### ISSUE THREAD

**Issue by Jens10123** [Palakis/obs-ndi#140]
Wanted to install NDI with the Windows Installer and descovered that the download server is down.

**Comment by Palakis** [comment]
Releases are hosted on GitHub and I have no control on this. It should be fixed by now.

**Comment by Jens10123** [comment]
![5](https://user-images.githubusercontent.com/37872605/38089483-d5f9232c-335f-11e8-949f-e422c54478be.PNG)

See ^^ it's still down

**Comment by Helgaiden** [comment]
downloaded and updated on two PCs from the OBS NDI main plugin page yesterday at around 6pm PST. 

Worked for me.

**Comment by Jens10123** [comment]
But I also need the runtime. If I click on the link to download the runtime manually, i also get an error...
![unbenannt](https://user-images.githubusercontent.com/37872605/38146839-0237dadc-3450-11e8-83b7-469ee64a8bc2.PNG)

**Comment by Jens10123** [comment]
Just want to mention, that this problem is still existing...

**Comment by junglistttt** [comment]
I am trying to dowload OBS-NDI 4.3.0 for the first time today and I am also getting errors that the server is down.  Really wanted to give this a try, wish I would have heard of it sooner so I could at least have downloaded it.

**Comment by Helgaiden** [comment]
@Jens10123 @junglistttt 
https://github.com/Palakis/obs-ndi/releases/tag/4.3.0

From there? Works just fine for me. Check your adblockers, anti-virus, or any other scanning software that might be filtering your downloads. Try downloading with a different browser as well. Stuff like that.

**Comment by junglistttt** [comment]
@Helgaiden 

Wow, thanks for the fast comment! That is the site that I was getting it from. I will turn off adblock, and if that doesn't work, I will switch browsers. 

Thanks.

**Comment by Jens10123** [comment]
Still not working...I turned off adblock (not understanding why this should make any difference with the windows installer) and windows firewall and still get the same error posted above and can't even access the website do download the runtime manually.

**Comment by rachmatROSS** [comment]
any solution yet cant donwload the runtime ?

**Comment by Thekowo** [comment]
Same issue, would love to find a solution, tried the addblock stuff and it made 0 difference

**Comment by mpapazog** [comment]
Same issue. new.tk responds to ping, but the NDI redistributable link does not work. Are there any alternate sources to download the runtime?

**Comment by MagicMaxMan007** [comment]
Same at me... :( Need this really.... But the Servers are down.... :( 

How can i get the Runtime now?

**Comment by Palakis** [comment]
Grouping this into #403

**Comment by Palakis** [comment]
@MagicMaxMan007 Have a look here: https://slepin.fr/obs-ndi/runtime/
