### ISSUE TITLE
Audio shows up in the monitor levels, but the scene is muted when recorded.

### ISSUE THREAD

**Issue by ryanjpodonnell** [Palakis/obs-ndi#429]
I cannot figure out how to get sound during a recording with OBS 25.0.4 on windows 10 using the NDI HX Camera app on an iPhone. I also could not get this working with OBS 24.0.4 (I saw that people were having luck reverting to an older version).

I can see the sound levels in the monitor, but when viewing the recorded video there is no audio. If I add another microphone to the scene, the audio is super choppy and unusable...

When editing the advanced sound option I can hear feedback from the phone when I edit the output monitoring. However, still a muted scene when viewing a recorded video.

I recently got a Windows 10 laptop and have had no luck with the NDI source. The video looks great tho. This was working fine on my mac. Any ideas?

**Comment by Danjuanlab** [comment]
I also encountered the same problem as you, but I used the camera + NDI wireless image transmission, the audio I received in OBS was intermittent, and the volume seemed to be obviously increased by 10dB, and the volume of NDI Studio monitor completely different.

**Comment by BillyBob1354** [comment]
I have this same issue. When using the NDI HX Camera app for the iPhone, I can see audio levels and can hear it when monitoring is enabled, but during recording there is no audio even from different sources.

The logs show that the audio buffer for the NDI source immediately fills to max as soon as OBS is opened. This probably is why the audio stops working.

**Comment by jimtran93** [comment]
I am having this same issue, using plugin version 4.5.2.0, NDI HX Camera version 2.1 for iOS, and OBS version 25.0.4 on a Windows 10 machine. I documented some troubleshooting on the OBS forums: https://obsproject.com/forum/threads/ndi-source-audio-not-recording.118754/#post-450485

**Comment by mathewda** [comment]
I'm also having this issue. I don't get any sound in my recording but see audio in the source monitor. I did discover that until I get the buffer full messages in my log file that it does work ok, but as soon as the buffer message shows up then the sound no longer works in the recording for that source.

I've experienced this issue with both my iPhone 6 and an iPad Pro 2018. Using NDI tools 4.5, plugin version 4.8 and OBS 25.0.4 - 64bit

**Comment by douglas-jordan** [comment]
I have same the issue,and alsoposted on the obs forum thread @jimtran93 mentioned. Running Windows 10 and iPhone Xr all latest software versions.

I noted in the mp4 file the audio bitrate shows 2kbps in media player, that must be a default or minimum value as I do not have it set for that.

The audio glitches when going from a scene with audio to the NDI source from NDI-HX app and when the scene transition completes there is no audio.

**Comment by sfbrian** [comment]
I'm running into the same exact issue that @ryanjpodonnell is experiencing. It worked fine on Mac but when I switched to a Windows machine I don't get any audio from the NDI source. I can hear it on the monitor and the sound bar moves when I speak into the iPhone. When I add another mic source I get all sorts of pops and choppyness.

**Comment by SplitCoreGaming** [comment]
Also can confirm above issue.

**Comment by mattbaird** [comment]
I am also experiencing this issue and it makes using the Skype --> NDI --> OBS chain unusable.

**Comment by bufanda** [comment]
I have the same issue. Both with Version 4.8 and 4.9. But downgrading to 4.7.1 helped on this version the recoding is still working. 
I use OBS Version 25.0.8 and have Windows 10 2004 64bit running.

**Comment by Topsn** [comment]
got it:
we still know it´s a plugin problem but where exactly?
the problem is the "SYNC" mode in the ndi source settings. i only get a sound singal in streaming and record when i´m in "INTERNAL" mode.
In NDI 4.9 there is no INTERNAL mode anymore.
Thats why you can`t record the sound!!

i don`t know why but is the status quo.
we have to work with that settings until the bug is away

**Comment by Topsn** [comment]
But there is a "new" Problem:
The NDI HX app works but I have every 4-5 seconds a small leak problem with the video!
really strange, because: not on my Mac only on PC!
That's why it have to be a plugin problem on pc!
with the app OBS CAMERA everything works greats

**Comment by streamia-livestreaming** [comment]
**The solution**, for me:
NDI Source properties: Sync/Network

OBS version: 26, 27
OBS NDI Plugin version: 4.9.0

**Comment by Trouffman** [comment]
Update on this bug.

So if OBS is launched with an NDI source in "Audio Only", this will use the "audio only option" for geting the NDI Stream, That source's audio leve will show up in the monitor but NOT on the track monitor (when using OBS Music Edition.

This is happenning after Audio decoding but before being added to the audio track.

One of the workround ( that I explained on another ticket) : go in the NDI Source, then select another bandwidth type,save, re-edit that source, put back in Audio Only) - This needs to be done everytime.
> Also this seems to still use the full bandwidth NDI Feed and not display it.

**Comment by Trouffman** [comment]
One of the workround ( that I explained on another ticket) : go in the NDI Source, then select another bandwidth type,save, re-edit that source, put back in Audio Only) - This needs to be done everytime.

Also this seems to still use the full bandwidth NDI Feed and not display it.

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by Trouffman** [comment]
As tested :
Windows 11

- Launch OBS
- Configure the NDI input source
- audio only - no hardware accelleration - source timing 
![image](https://user-images.githubusercontent.com/2151317/222435263-ba1c14d2-2afb-4179-87e5-ec21dd533a29.png)
- close all OBS
- launch OBS
- press rec (do not do anythign else)

(only one audio track!) 

Result:
Audio still missing from the the recording.

BUT if you use Sync "network" the audio is there as expected.

THis is onemore reason to reconsider the sync timing challenge in : #479

**Comment by paulpv** [comment]
Interesting.
The current code for Sync `Network` vs `Source Timing` is:
https://github.com/obs-ndi/obs-ndi/blob/4daba126d0fc294a9f38213d9fb0a5a6b914c4ee/src/obs-ndi-source.cpp#L368-L380

I didn't write this code, so I am just saying as the current code maintainer that this option is obviously there for a reason.
Is the existence of this option enough to close this Issue?

**Comment by swspcodes** [comment]
> One of the workround ( that I explained on another ticket) : go in the NDI Source, then select another bandwidth type,save, re-edit that source, put back in Audio Only) - This needs to be done everytime.
> 
> Also this seems to still use the full bandwidth NDI Feed and not display it.

Thanks for showing me the way. This works and is indeed a path for the developers to find the root of the problem.

**Comment by paulpv** [comment]
Any suggestions on how the code should change here?

**Comment by swspcodes** [comment]
> Any suggestions on how the code should change here?

Unfortunately I only work amateurly with PHP, so I wouldn't know. But maybe refreshing that setting somehow when OBS launches, or re-setting it to the same value could be an ugly workaround?

**Comment by paulpv** [comment]
We are setting that setting when the NDI Source is created:
https://github.com/obs-ndi/obs-ndi/blob/7fe10f551d6629399477c274cc66eb768152ea21/src/obs-ndi-source.cpp#L955-L956

**ALWAYS** called by `ndi_source_create`:
https://github.com/obs-ndi/obs-ndi/blob/7fe10f551d6629399477c274cc66eb768152ea21/src/obs-ndi-source.cpp#L1038

**Comment by swspcodes** [comment]
> We are setting that setting when the NDI Source is created:
> 
> https://github.com/obs-ndi/obs-ndi/blob/7fe10f551d6629399477c274cc66eb768152ea21/src/obs-ndi-source.cpp#L955-L956
> 
> **ALWAYS** called by `ndi_source_create`:
> 
> https://github.com/obs-ndi/obs-ndi/blob/7fe10f551d6629399477c274cc66eb768152ea21/src/obs-ndi-source.cpp#L1038

My suggestion, being an amateur in coding (I'm just a user who this tool really helps me in my music DAW tutorials work), would be to somehow refresh this setting. It would be an emulation of what we have to do to be able to record the audio coming from the NDI source. 

Like @Trouffman explained, we have to set the bandwidth to another setting, save, and re-set it to our preferred setting every time we open OBS, to be able to actually record the audio in the video OBS recording. So it's an ugly workaround, but if the coder could emulate this somehow, it would help the users and would appear as though there is no bug in this case.

**Comment by paulpv** [comment]
I wish I could find in the code where that isn't already happening :)

**Comment by paulpv** [comment]
Related to https://github.com/obs-ndi/obs-ndi/issues/906 ?

**Comment by ss44** [comment]
this one's been driving me a bit crazy, it seems like the switching quality trick does seem too help.

Wonder if doing the toggle in code as @swspcodes proposed would help. 

Going to try making it and building it locally, to experiment, hopefully the build process isn't too tricky.

**Comment by paulpv** [comment]
@ss44 go for it. My reviews of the code in this area looks like the code is written correctly.
I am not sure where to better set this.
It'd be great if you can find another place and the code doesn't look like a hack.

**Comment by Trouffman** [comment]
@paulpv I gave it a read / look as well.
This problem only exist at the initial launch of OBS.

Seems that fail to create the empty frame.

Here is launching OBS with 1 NDI scene, with highest bandwidth :
`01:46:12.718: ------------------------------------------------
01:46:12.723: [obs-ndi] ndi_source_shown('test pattern'...)
01:46:12.723: [obs-ndi] ndi_source_activated('test pattern'...)
01:46:12.727: [obs-ndi] ndi_source_thread: 'OBS-NDI 'test pattern'' -ndi_receiver = ndiLib->recv_create_v3(&recv_desc)
01:46:14.001: Attempted path: data/obs-studio/images/overflow.png
01:46:14.002: Attempted path: ../../data/obs-studio/images/overflow.png
`

Here is the exact same config (new start of OBS) but with the NDI source set as "audio only"
`01:44:58.806: ------------------------------------------------
01:44:58.809: [obs-ndi] ndi_source_thread: 'OBS-NDI 'test pattern'' -ndi_receiver = ndiLib->recv_create_v3(&recv_desc)
01:44:58.823: device_texture_create (D3D11): Failed to create 2D texture (80070057)
01:44:58.823: [obs-ndi] ndi_source_shown('test pattern'...)
01:44:58.823: [obs-ndi] ndi_source_activated('test pattern'...)
01:44:58.823: gs_texture_get_color_format: Null 'tex' parameter
01:44:59.300: Attempted path: data/obs-studio/images/overflow.png
01:44:59.300: Attempted path: ../../data/obs-studio/images/overflow.png
`

The "device_texture_create (D3D11): Failed to create 2D texture (80070057)" is there even when you select it in the menu (but IIRC that "audio only" mode flat-out do not work for some.

`01:51:06.384: [obs-ndi] -ndi_source_update('test pattern'...)
01:51:06.457: [obs-ndi] ndi_source_thread: 'OBS-NDI 'test pattern'' bandwidth changed; Setting recv_desc.bandwidth='10'
01:51:06.457: [obs-ndi] ndi_source_thread: 'OBS-NDI 'test pattern'' Resetting NDI receiver...
01:51:06.457: [obs-ndi] ndi_source_thread: 'OBS-NDI 'test pattern'' ndiLib->recv_destroy(ndi_receiver)
01:51:06.458: [obs-ndi] ndi_source_thread: 'OBS-NDI 'test pattern'' +ndi_receiver = ndiLib->recv_create_v3(&recv_desc)
01:51:06.461: [obs-ndi] ndi_source_thread: 'OBS-NDI 'test pattern'' -ndi_receiver = ndiLib->recv_create_v3(&recv_desc)
01:51:06.484: device_texture_create (D3D11): Failed to create 2D texture (80070057)
01:51:06.484: gs_texture_get_color_format: Null 'tex' parameter`

Another reason i see could be a config var that is not set when going to audio_only by default, but is set if bandwidth is set / selected.


This seems tied up to : `blank_video_frame()` which likely does not like the parameters
`obs_source_frame_create(VIDEO_FORMAT_NONE, 0, 0);`
I could not find docs or reference to this "obs_source_frame_create" anywhere. maybe that is the culprit here.

**Comment by paulpv** [comment]
> This seems tied up to : blank_video_frame() which likely does not like the parameters
obs_source_frame_create(VIDEO_FORMAT_NONE, 0, 0);
I could not find docs or reference to this "obs_source_frame_create" anywhere. maybe that is the culprit here.

https://github.com/obsproject/obs-studio/blob/master/libobs/obs.h#L2737
```
static inline struct obs_source_frame *
obs_source_frame_create(enum video_format format, uint32_t width,
			uint32_t height)
{
	struct obs_source_frame *frame;

	frame = (struct obs_source_frame *)bzalloc(sizeof(*frame));
	obs_source_frame_init(frame, format, width, height);
	return frame;
}
```

**Comment by swspcodes** [comment]
Hi guys, some good news here.

I upgraded to Windows 11 and ran all windows updates, most recent version of OBS, NDI tools 6, and removed the AMD Adrenalin Edition software, installing Drivers only for my GPU (Adrenalin software is a hijacker of resources, interfering with a lot of software, and I don't do games so it seems unnecessary for my usage). 

Now it works, I can set up the NDI plugin in my DAW with OBS already running, whatever I do, it just works. Recording is getting the DAW sound, system sound, everything perfect. 

I think this has been fixed somehow with the Updates I mentioned above.

**Comment by Trouffman** [comment]
Gong back to this as this is a recurring issue.

More detail :

**Comment by Trouffman** [comment]
Going back to this as this is a recurring issue ans still exists (even in 6.0.0-alpha)

More detail using the obs-ndi debug option
`info: [obs-ndi] ndi_source_shown('NDI Source 1'...)
info: [obs-ndi] ndi_source_activated('NDI Source 1'...)
info: [obs-ndi] ndi_source_thread_start: 'OBS-NDI 'NDI Source 1'' Started A/V ndi_source_thread for NDI source 'TROUFFAIR.LOCAL (Test Patterns)'
info: [obs-ndi] +ndi_source_thread('NDI Source 1'...)
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' ndi_receiver_name changed; Setting recv_desc.p_ndi_recv_name='OBS-NDI 'NDI Source 1''
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' ndi_source_name changed; Setting recv_desc.source_to_connect_to.p_ndi_name='TROUFFAIR.LOCAL (Test Patterns)'
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' bandwidth changed; Setting recv_desc.bandwidth='10'
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' latency changed; Setting recv_desc.color_format='1'
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' Resetting NDI receiver...
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' +ndi_receiver = ndiLib->recv_create_v3(&recv_desc)
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' -ndi_receiver = ndiLib->recv_create_v3(&recv_desc)
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
info: [obs-ndi] ndi_source_thread: 'OBS-NDI 'NDI Source 1'' tally changed; Sending tally on_preview=1, on_program=1`

The "UNSUPPORTED" error seems to be the hint!
Could be because it is trying to create a frame with height/width of 0. but it does not seems to cause other issues.

https://github.com/obs-ndi/obs-ndi/blob/9a79399d3df2cf277a670644389a6df6d8727bbd/src/obs-ndi-source.cpp#L200-L206

There is no mention is this could be a reason/challenge as well.
https://docs.obsproject.com/reference-sources?highlight=obs_source_frame#c.obs_source_info.filter_video


Other avenue to look at:

When set to Audio only ; this create the Audio audio frame directly at
https://github.com/obs-ndi/obs-ndi/blob/9a79399d3df2cf277a670644389a6df6d8727bbd/src/obs-ndi-source.cpp#L497-L503
Two things here:
- Was there a reason to have this call `obs_source_output_video` right away instead of like the 2 other options?
- Should this use the obs_source_output_audio instead ? (not sure as maybe we need "some" video frame for timing ?)
https://docs.obsproject.com/reference-sources#c.obs_source_output_audio

I did not had time to check / update the code for this yet. If anyone wants to get a try

**Comment by Trouffman** [comment]
I found the issue in the way the plugin behave for the audio only. PR coming soon.

Short version : 
There are 2 challenges: 
- creating the blank frame with 0 0 trigger an error BUT this was not the root cause (it sent me a on a different rabbit hole)

- The way we created the audio_only settings was applied only when the settings changed and not consistent with the general behavior of the plugin.


### For future reference on the "blank_frame issue" (not linked to the audio issue)
When creating the "first" frame, the plugin will make one that is actually 0x0 resolution, this trigger an error in OBS because nothing can be drawn in 0x0. Using 1x1 does help the error to not appear but this is NOT a proper way of doing as this will generate a 1x1 pixel and be visible. 
https://github.com/obs-ndi/obs-ndi/blob/d889c2bf2bc749637a32df198f1d7fdc7df0d70e/src/obs-ndi-source.cpp#L200-L205

Error with 0x0 resolution is : 
device_texture_create (D3D11): Failed to create 2D texture (80070057)
gs_texture_get_color_format: Null 'tex' parameter

If resolution is at least one pixel, this will not trigger the "device_texture_create (D3D11): Failed to create 2D texture (80070057)" error. But this will display a pixel on the source.

Maybe this could be using the : https://docs.obsproject.com/reference-sources#c.obs_source_output_video
`obs_source_output_video()` and set it to `NULL`

**Comment by Trouffman** [comment]
This has been fixed in DistroAV 6.0.0
