### ISSUE TITLE
NDI Output Sending Audio Permanent.

### ISSUE THREAD

**Issue by virtunite** [Palakis/obs-ndi#457]
The Dedicated NDI Output is permanently sending the audio when added as a filter to (for example) a Mic even when it is muted.
Example Picture below.

Audio output is muted, second PC still gets audio wich shouldn't be the case.
![ndi](https://user-images.githubusercontent.com/64329594/80292075-e6ab9680-875b-11ea-8abf-5ed53f8ed023.PNG)

Hoping for a fast fix.

**Comment by walterav1984** [comment]
@virtunite which NDI version and OBS-ndi plugin version are you using and it seems you have plugins/addons installed? 

I guess this is not a bug but it may because of technical implementation...

**Comment by virtunite** [comment]
I use the latest obs and ndi for obs version. To make that clearer again: my second PC is receiving an audio signal, even when the mic is muted in obs. obviously the mic in obs on my main pc is muted when i mute it.

**Comment by walterav1984** [comment]
> I use the latest obs and ndi for obs version.

Which is obs-ndi 4.9 released 12 hours ago and obs studio 25.08? BTW can you change your issue title to includec dedicated or filter NDI output?

**Comment by walterav1984** [comment]
Possible duplicate of #138

**Comment by dinther** [comment]
Maybe I can shed some more light on the issue raised. Audio and video filters on a source are respected and affect what can be seen and heard on the receiving end of the NDI feed. However, Audio volume and or mute settings can not.

Example:
I can put a gain audio filter on a source and send it out via your NDI filter object. On the receiving end of the NDI feed the effect of the gain filter can be heard in the audio volume. However when I adjust the volume or mute the audio source on the audio mix panel then the audio remains audible unchanged.

For now I have no option but to route audio outside of OBS.

**Comment by tomazzaman** [comment]
I found this thread while searching for a solution. I have all my audio channels (4 of them) defined in sources, but none get muted when I switch to "BRB" screen in OBS.  #138 is supposed to solve that but it's been on the to-do list for quite some time :/

**Comment by rave2n** [comment]
Says #138 is solved in 3.8, but is not reflecting such in 3.9 or 3.10.

**Comment by incith** [comment]
Using dedicated output filter on my Mic/Aux, muting it does nothing, the streaming PC still captures everything.

I see a lot of threads saying this was going to be fixed, duplicate of this issue, duplicate of that issue.  Well I'm here to say it is still happening.  OBS 29.1.3, NDI whatever the latest is I just downloaded it from github yesterday.

**Comment by rave2n** [comment]
Yep, still does it for me even after using the latest at greatest. 

I ended up just muting the source and unmuting when I use push to talk - Its voicemeter, so can just set a button to do such.

**Comment by Davi-DemK** [comment]
> Using dedicated output filter on my Mic/Aux, muting it does nothing, the streaming PC still captures everything.
> 
> I see a lot of threads saying this was going to be fixed, duplicate of this issue, duplicate of that issue. Well I'm here to say it is still happening. OBS 29.1.3, NDI whatever the latest is I just downloaded it from github yesterday.
> 
> If using the main "NDI Output" - output Main channel.. and I add that as a source, the audio mutes properly between gaming to streaming PC. But just the dedicated NDI filters do not work this way.

Same here, OBS 30.0.2 and the problem seems to still happen. Even when olds topics tagged as duplicated, already "fixed" in version 4.8.0 ( but seems not ). I hope they fix that, its the only annoying issue at least to me to use NDI.

**Comment by Trouffman** [comment]
Could be similar as : 
- https://github.com/DistroAV/DistroAV/issues/1219
- https://github.com/DistroAV/DistroAV/pull/1266
- https://github.com/DistroAV/DistroAV/pull/1232

**Comment by incith** [comment]
Thank you. I feel noticed 😂

**Comment by RayneYoruka** [comment]
To add on this, if I don't remember wrong these is "normal behaviour", I see this with all filters within OBS regardless of NDI or not, perhaps these is a limitation of OBS itself? Mentioning from the top of my head.

"Workaround" has been to mute on destination with something like a streamdeck/touch portal/streamerbot.

**Comment by Trouffman** [comment]
@BitRate27 -> Maybe we can add an option "Follow Source Status" (boolean) -> default is false (to stay backward compatible and keep the historical behaviour.

-> if enabled, this would follow the settings:
- Mute / unmute -> but keep sending/processing the data
- Active/Inactive -> We can define to "stop the sender" in this case

**Comment by Trouffman** [comment]
Up on this.

We discussed this recently as we made the requested behavior on the video filter (for totally different reasons tho).
